In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns = ['cgpa','profile_score','lpa'])

In [3]:
data.head()

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [4]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

2024-08-09 13:57:23.498544: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-08-09 13:57:23.498694: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-08-09 13:57:23.674498: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


In [5]:
model = Sequential()

model.add(Dense(2, activation='linear',input_dim=2))
model.add(Dense(1, activation='linear'))

model.summary()

/opt/conda/lib/python3.10/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [6]:
model.get_weights()

[array([[-0.90275586,  0.4366325 ],
        [ 1.0061275 , -1.0646951 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.7336215 ],
        [-0.42177027]], dtype=float32),
 array([0.], dtype=float32)]

In [7]:
new_weights = [np.array([[0.1,0.1],
                       [0.1,0.1]], dtype=np.float32),
               np.array([0.,0.],dtype=np.float32),
               np.array([[0.1],
                         [0.1]], dtype=np.float32),
                np.array([0.], dtype=np.float32)
              
              ]

In [8]:
model.set_weights(new_weights)

In [9]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [10]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [11]:
model.fit(data.iloc[:,0:-1].values,data['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 31.8140
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 24.1377 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 23.8370 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 24.0344 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 24.3830 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 30.0071 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 25.4905 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 25.7495 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 28.7834 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 24.2545 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 23.8803 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21.7868 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 24.1256 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 24.4685 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20.5258
Epoch 16/75
4/4 ━━━━━

In [12]:
model.get_weights()

[array([[0.37356174, 0.37356174],
        [0.36544326, 0.36544326]], dtype=float32),
 array([0.272214, 0.272214], dtype=float32),
 array([[0.37281367],
        [0.37281367]], dtype=float32),
 array([0.20464635], dtype=float32)]